export const refs = {
  artistsList: document.querySelector('.artists-list'),
  containerEL: document.querySelector('.container'),
  loader: document.querySelector('.loader'),
  artistsPagination: document.querySelector('#artists-pagination'),
  feedbackContainer: document.querySelector('.section-feedback .container'),
  genreSelect: document.querySelector('#genre-select'),
  sortSelect: document.querySelector('#sort-select'),
  searchInput: document.querySelector('.filters-search-input'),
  searchBtn: document.querySelector('.filters-search-btn'),
  resetBtn: document.querySelector('.filters-reset-btn'),
  emptyResetBtn: document.querySelector('.empty-reset-btn'),
  toggleBtn: document.querySelector('.filters-toggle-btn'),
  filtersWrapper: document.querySelector('.filters-wrapper'),
  artistsLoader: document.querySelector('.artists-loader'),
  modalArtistLoader: document.querySelector('.modal-artist-loader'),
  headerEl: document.querySelector('.header'),
  artistsEl: document.querySelector('.section-artists'),
};
